import type { Account, Bank, Category, CreateExpenseInput, CreditCard, Expense, ExpenseInstallment, Id, InvestmentGoal, InvestmentPosition, InvoiceDetails, MonthlyReport, Receivable, RecurringExpense, Subscription, User } from '@/lib/types';
const baseUrl = (process.env.EXPO_PUBLIC_API_URL || 'http://localhost:8080').replace(/\/$/, '');
export class ApiError extends Error { constructor(message: string, public status: number) { super(message); } }
async function request<T>(path: string, init?: RequestInit): Promise<T> { let response: Response; try { response = await fetch(`${baseUrl}${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } }); } catch { throw new ApiError('Não foi possível acessar a API local. Confirme se o backend está em http://localhost:8080.', 0); } if (!response.ok) { const body = await response.json().catch(() => null) as { message?: string; detail?: string; error?: string } | null; const fallback = response.status === 404 ? 'A rota da API não foi encontrada. Reinicie o backend para carregar a versão atual.' : `A API recusou esta ação (HTTP ${response.status}).`; throw new ApiError(body?.message || body?.detail || body?.error || fallback, response.status); } return response.status === 204 ? (undefined as T) : response.json() as Promise<T>; }
const userPath = (userId: Id, path: string) => `/api/users/${userId}${path}`;
export const api = {
  createUser: (body: { name: string; email: string }) => request<User>('/api/users', { method: 'POST', body: JSON.stringify(body) }), getUser: (id: Id) => request<User>(`/api/users/${id}`), findUserByEmail: (email: string) => request<User>(`/api/users/by-email?email=${encodeURIComponent(email)}`),
  listBanks: (id: Id) => request<Bank[]>(userPath(id, '/banks')), createBank: (id: Id, body: Pick<Bank, 'name' | 'code' | 'type'>) => request<Bank>(userPath(id, '/banks'), { method: 'POST', body: JSON.stringify(body) }),
  listAccounts: (id: Id) => request<Account[]>(userPath(id, '/accounts')), createAccount: (id: Id, body: { bankId: Id; name: string; type: Account['type'] }) => request<Account>(userPath(id, '/accounts'), { method: 'POST', body: JSON.stringify(body) }),
  listCategories: (id: Id) => request<Category[]>(userPath(id, '/categories')), createCategory: (id: Id, body: { name: string; color: string }) => request<Category>(userPath(id, '/categories'), { method: 'POST', body: JSON.stringify(body) }),
  listCards: (id: Id) => request<CreditCard[]>(userPath(id, '/credit-cards')), createCard: (id: Id, body: Omit<CreditCard, 'id' | 'userId' | 'active'>) => request<CreditCard>(userPath(id, '/credit-cards'), { method: 'POST', body: JSON.stringify(body) }), invoice: (id: Id, cardId: Id, year: number, month: number) => request<InvoiceDetails>(userPath(id, `/credit-cards/${cardId}/invoices/${year}/${month}`)), setCurrentInvoiceTotal: (id: Id, cardId: Id, totalAmount: number) => request<unknown>(userPath(id, `/credit-cards/${cardId}/invoices/current-total`), { method: 'PUT', body: JSON.stringify({ totalAmount }) }),
  listExpenses: (id: Id) => request<Expense[]>(userPath(id, '/expenses')), createExpense: (id: Id, body: CreateExpenseInput) => request<{ expense: Expense; installments: ExpenseInstallment[] }>(userPath(id, '/expenses'), { method: 'POST', body: JSON.stringify(body) }),
  listSubscriptions: (id: Id) => request<Subscription[]>(userPath(id, '/subscriptions')), createSubscription: (id: Id, body: Omit<Subscription, 'id' | 'userId' | 'active'>) => request<Subscription>(userPath(id, '/subscriptions'), { method: 'POST', body: JSON.stringify(body) }), report: (id: Id, year: number, month: number) => request<MonthlyReport>(userPath(id, `/reports/monthly?year=${year}&month=${month}`)),
  investments: (id: Id, year: number, month: number) => request<InvestmentPosition[]>(userPath(id, `/planning/investments?year=${year}&month=${month}`)), saveInvestment: (id: Id, body: { institution: string; year: number; month: number; amount: number }) => request<InvestmentPosition>(userPath(id, '/planning/investments'), { method: 'PUT', body: JSON.stringify(body) }), goal: (id: Id) => request<InvestmentGoal | null>(userPath(id, '/planning/investment-goal')), saveGoal: (id: Id, body: { targetAmount: number; targetDate: string }) => request<InvestmentGoal>(userPath(id, '/planning/investment-goal'), { method: 'PUT', body: JSON.stringify(body) }),
  receivables: (id: Id) => request<Receivable[]>(userPath(id, '/planning/receivables')), createReceivable: (id: Id, body: { personName: string; description: string; amount: number; dueDate: string }) => request<Receivable>(userPath(id, '/planning/receivables'), { method: 'POST', body: JSON.stringify(body) }), receive: (id: Id, receivableId: Id) => request<Receivable>(userPath(id, `/planning/receivables/${receivableId}/receive`), { method: 'PUT' }), cancelReceivable: (id: Id, receivableId: Id) => request<Receivable>(userPath(id, `/planning/receivables/${receivableId}/cancel`), { method: 'PUT' }),
  recurringExpenses: (id: Id) => request<RecurringExpense[]>(userPath(id, '/planning/recurring-expenses')), createRecurringExpense: (id: Id, body: Omit<RecurringExpense, 'id' | 'userId' | 'active'>) => request<RecurringExpense>(userPath(id, '/planning/recurring-expenses'), { method: 'POST', body: JSON.stringify(body) }), confirmRecurringExpense: (id: Id, recurringId: Id, year: number, month: number) => request<unknown>(userPath(id, `/planning/recurring-expenses/${recurringId}/confirm`), { method: 'POST', body: JSON.stringify({ year, month }) }), deactivateRecurringExpense: (id: Id, recurringId: Id) => request<RecurringExpense>(userPath(id, `/planning/recurring-expenses/${recurringId}/deactivate`), { method: 'PUT' }),
};
